version: '3.8'
services:
  php_app_name:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - .:/var/www

  nginx_app_name:
    image: ngnix-web
    platform: linux/x86_64
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    working_dir: /var/www
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/public
    depends_on:
      - php_app_name

  db_app_name:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_ROOT_PASSWORD: secret_root
      MYSQL_USER: app_user
      MYSQL_PASSWORD: secret
    ports:
      - "33064:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
