# Using the official Nginx image as the base image for the container, change/upgrade as needed
FROM nginx:1.10

# Copy custom configuration file from the current directory
COPY vhost.conf /etc/nginx/conf.d/default.conf
